local M = {}

local function focus_config()
	return (((require("udebugtool.config").values or {}).debug or {}).focus or {})
end

local function powershell_command()
	for _, candidate in ipairs({ "powershell.exe", "pwsh.exe", "powershell", "pwsh" }) do
		if vim.fn.executable(candidate) == 1 then
			return candidate
		end
	end
	return nil
end

local function script()
	return table.concat({
		"$ErrorActionPreference = 'SilentlyContinue'",
		"$sourcePid = [int]$args[0]",
		"$restore = [int]$args[1]",
		"$topmostMs = [int]$args[2]",
		"$pidChain = New-Object 'System.Collections.Generic.HashSet[int]'",
		"$pidCursor = $sourcePid",
		"for ($i = 0; $i -lt 10 -and $pidCursor -gt 0; $i++) {",
		"  [void]$pidChain.Add($pidCursor)",
		"  $proc = Get-CimInstance Win32_Process -Filter \"ProcessId=$pidCursor\"",
		"  if (-not $proc) { break }",
		"  $pidCursor = [int]$proc.ParentProcessId",
		"}",
		"Add-Type -Namespace UDebugTool -Name Win32 -MemberDefinition @'",
		"using System;",
		"using System.Runtime.InteropServices;",
		"using System.Text;",
		"public static class Native {",
		"  public delegate bool EnumWindowsProc(IntPtr hWnd, IntPtr lParam);",
		"  [DllImport(\"kernel32.dll\")] public static extern IntPtr GetConsoleWindow();",
		"  [DllImport(\"kernel32.dll\")] public static extern uint GetCurrentThreadId();",
		"  [DllImport(\"user32.dll\")] public static extern bool EnumWindows(EnumWindowsProc callback, IntPtr lParam);",
		"  [DllImport(\"user32.dll\")] public static extern bool IsWindowVisible(IntPtr hWnd);",
		"  [DllImport(\"user32.dll\")] public static extern bool IsIconic(IntPtr hWnd);",
		"  [DllImport(\"user32.dll\")] public static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);",
		"  [DllImport(\"user32.dll\")] public static extern bool ShowWindowAsync(IntPtr hWnd, int nCmdShow);",
		"  [DllImport(\"user32.dll\")] public static extern bool SetForegroundWindow(IntPtr hWnd);",
		"  [DllImport(\"user32.dll\")] public static extern IntPtr GetForegroundWindow();",
		"  [DllImport(\"user32.dll\")] public static extern bool BringWindowToTop(IntPtr hWnd);",
		"  [DllImport(\"user32.dll\")] public static extern bool SetFocus(IntPtr hWnd);",
		"  [DllImport(\"user32.dll\")] public static extern bool SetActiveWindow(IntPtr hWnd);",
		"  [DllImport(\"user32.dll\")] public static extern bool AttachThreadInput(uint idAttach, uint idAttachTo, bool fAttach);",
		"  [DllImport(\"user32.dll\")] public static extern bool SetWindowPos(IntPtr hWnd, IntPtr hWndInsertAfter, int X, int Y, int cx, int cy, uint flags);",
		"  [DllImport(\"user32.dll\")] public static extern int GetWindowTextLengthW(IntPtr hWnd);",
		"  [DllImport(\"user32.dll\", CharSet=CharSet.Unicode)] public static extern int GetWindowTextW(IntPtr hWnd, StringBuilder text, int count);",
		"  [DllImport(\"user32.dll\")] public static extern uint GetWindowThreadProcessId(IntPtr hWnd, out uint processId);",
		"}",
		"'@",
		"$shell = $null",
		"try { $shell = New-Object -ComObject WScript.Shell } catch {}",
		"function Get-Title([IntPtr]$Handle) {",
		"  $length = [UDebugTool.Win32+Native]::GetWindowTextLengthW($Handle)",
		"  if ($length -le 0) { return '' }",
		"  $builder = New-Object System.Text.StringBuilder ($length + 1)",
		"  [void][UDebugTool.Win32+Native]::GetWindowTextW($Handle, $builder, $builder.Capacity)",
		"  return $builder.ToString()",
		"}",
		"function Get-CandidateFromProcessChain {",
		"  foreach ($pid in $pidChain) {",
		"    $process = Get-Process -Id $pid -ErrorAction SilentlyContinue",
		"    if ($process -and $process.MainWindowHandle -ne 0) {",
		"      return [IntPtr]$process.MainWindowHandle",
		"    }",
		"  }",
		"  return [IntPtr]::Zero",
		"}",
		"function Get-CandidateFromWindows {",
		"  $bestHandle = [IntPtr]::Zero",
		"  $bestPid = 0",
		"  $bestScore = -1",
		"  $callback = [UDebugTool.Win32+Native+EnumWindowsProc]{",
		"    param([IntPtr]$hWnd, [IntPtr]$lParam)",
		"    if (-not [UDebugTool.Win32+Native]::IsWindowVisible($hWnd)) { return $true }",
		"    $title = Get-Title $hWnd",
		"    [uint32]$ownerPid = 0",
		"    [void][UDebugTool.Win32+Native]::GetWindowThreadProcessId($hWnd, [ref]$ownerPid)",
		"    if ($ownerPid -eq 0) { return $true }",
		"    $proc = Get-Process -Id $ownerPid -ErrorAction SilentlyContinue",
		"    if (-not $proc) { return $true }",
		"    $name = ($proc.ProcessName | Out-String).Trim().ToLowerInvariant()",
		"    $score = 0",
		"    if ($pidChain.Contains([int]$ownerPid)) { $score += 400 }",
		"    if ($name -match 'windowsterminal|wezterm|alacritty|conemu|mintty|cmd|pwsh|powershell') { $score += 120 }",
		"    $lowerTitle = ($title | Out-String).Trim().ToLowerInvariant()",
		"    if ($lowerTitle -match 'nvim') { $score += 60 }",
		"    if ($lowerTitle -match 'powershell|pwsh|cmd') { $score += 20 }",
		"    if ($score -gt $bestScore) {",
		"      $script:bestScore = $score",
		"      $script:bestHandle = $hWnd",
		"      $script:bestPid = [int]$ownerPid",
		"    }",
		"    return $true",
		"  }",
		"  [void][UDebugTool.Win32+Native]::EnumWindows($callback, [IntPtr]::Zero)",
		"  return @{ Handle = $bestHandle; Pid = $bestPid; Score = $bestScore }",
		"}",
		"function Invoke-Foreground([IntPtr]$Handle) {",
		"  if ($Handle -eq [IntPtr]::Zero) { return }",
		"  $foreground = [UDebugTool.Win32+Native]::GetForegroundWindow()",
		"  [uint32]$foregroundPid = 0",
		"  $foregroundThread = 0",
		"  if ($foreground -ne [IntPtr]::Zero) {",
		"    $foregroundThread = [UDebugTool.Win32+Native]::GetWindowThreadProcessId($foreground, [ref]$foregroundPid)",
		"  }",
		"  [uint32]$targetPid = 0",
		"  $targetThread = [UDebugTool.Win32+Native]::GetWindowThreadProcessId($Handle, [ref]$targetPid)",
		"  $currentThread = [UDebugTool.Win32+Native]::GetCurrentThreadId()",
		"  $attachedForeground = $false",
		"  $attachedTarget = $false",
		"  try {",
		"    if ($foregroundThread -gt 0 -and $foregroundThread -ne $currentThread) {",
		"      $attachedForeground = [UDebugTool.Win32+Native]::AttachThreadInput($currentThread, $foregroundThread, $true)",
		"    }",
		"    if ($targetThread -gt 0 -and $targetThread -ne $currentThread) {",
		"      $attachedTarget = [UDebugTool.Win32+Native]::AttachThreadInput($currentThread, $targetThread, $true)",
		"    }",
		"    [void][UDebugTool.Win32+Native]::BringWindowToTop($Handle)",
		"    [void][UDebugTool.Win32+Native]::SetActiveWindow($Handle)",
		"    [void][UDebugTool.Win32+Native]::SetFocus($Handle)",
		"    [void][UDebugTool.Win32+Native]::SetForegroundWindow($Handle)",
		"    Start-Sleep -Milliseconds 60",
		"    [void][UDebugTool.Win32+Native]::BringWindowToTop($Handle)",
		"    [void][UDebugTool.Win32+Native]::SetForegroundWindow($Handle)",
		"  } finally {",
		"    if ($attachedTarget -and $targetThread -gt 0 -and $targetThread -ne $currentThread) {",
		"      [void][UDebugTool.Win32+Native]::AttachThreadInput($currentThread, $targetThread, $false)",
		"    }",
		"    if ($attachedForeground -and $foregroundThread -gt 0 -and $foregroundThread -ne $currentThread) {",
		"      [void][UDebugTool.Win32+Native]::AttachThreadInput($currentThread, $foregroundThread, $false)",
		"    }",
		"  }",
		"}",
		"function Focus-Handle([IntPtr]$Handle, [int]$OwnerPid) {",
		"  if ($Handle -eq [IntPtr]::Zero) { return }",
		"  if ($restore -eq 1 -and [UDebugTool.Win32+Native]::IsIconic($Handle)) {",
		"    [void][UDebugTool.Win32+Native]::ShowWindowAsync($Handle, 9)",
		"    Start-Sleep -Milliseconds 80",
		"  }",
		"  [void][UDebugTool.Win32+Native]::ShowWindowAsync($Handle, 5)",
		"  if ($topmostMs -gt 0) {",
		"    [void][UDebugTool.Win32+Native]::SetWindowPos($Handle, [IntPtr](-1), 0, 0, 0, 0, 0x0043)",
		"  }",
		"  if ($shell -and $OwnerPid -gt 0) {",
		"    try { [void]$shell.AppActivate($OwnerPid) } catch {}",
		"    try { $shell.SendKeys('%') } catch {}",
		"  }",
		"  Invoke-Foreground $Handle",
		"  if ($topmostMs -gt 0) {",
		"    Start-Sleep -Milliseconds $topmostMs",
		"    [void][UDebugTool.Win32+Native]::SetWindowPos($Handle, [IntPtr](-2), 0, 0, 0, 0, 0x0043)",
		"  }",
		"}",
		"$consoleHandle = [UDebugTool.Win32+Native]::GetConsoleWindow()",
		"if ($consoleHandle -ne [IntPtr]::Zero) {",
		"  [uint32]$consolePid = 0",
		"  [void][UDebugTool.Win32+Native]::GetWindowThreadProcessId($consoleHandle, [ref]$consolePid)",
		"  Focus-Handle $consoleHandle ([int]$consolePid)",
		"  exit 0",
		"}",
		"$processChainHandle = Get-CandidateFromProcessChain",
		"if ($processChainHandle -ne [IntPtr]::Zero) {",
		"  [uint32]$chainPid = 0",
		"  [void][UDebugTool.Win32+Native]::GetWindowThreadProcessId($processChainHandle, [ref]$chainPid)",
		"  Focus-Handle $processChainHandle ([int]$chainPid)",
		"  exit 0",
		"}",
		"$candidate = Get-CandidateFromWindows",
		"if ($candidate.Handle -ne [IntPtr]::Zero -and $candidate.Score -ge 0) {",
		"  Focus-Handle $candidate.Handle $candidate.Pid",
		"}",
	}, "\n")
end

function M.bring_to_front()
	local cfg = focus_config()
	if cfg.on_stopped == false or cfg.bring_to_front == false then
		return
	end
	if vim.fn.has("win32") ~= 1 then
		return
	end

	local shell = powershell_command()
	if not shell then
		return
	end

	pcall(vim.system, {
		shell,
		"-NoProfile",
		"-ExecutionPolicy",
		"Bypass",
		"-Command",
		script(),
		tostring(vim.fn.getpid()),
		cfg.restore_minimized == false and "0" or "1",
		tostring(tonumber(cfg.topmost_ms) or 0),
	}, {
		text = true,
		detached = true,
	})
end

return M
